### ISSUE TITLE
Initial UI/UX concept

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-discussify#12]
Create initial concept of UX/UI. A few considerations:

- Service has potentially 3 environments:
  - website
  - browsers extension
  - developer module / js library / plugin
- UI should account both for desktop and mobile platforms

**Comment by andreforsousa** [comment]
Here’s some of the studies we’ve been working before following the initial plan for Discussify, where different platforms were taken in consideration. Please note that for now we're only focusing on the desktop version.

- Web-app (w/ landing page draft)
    * https://drive.google.com/file/d/1_ntHspDj_hMgfpv_lC7t6_WjePNejKqZ/view
- Initial Style Guide (for web-app)
    * https://drive.google.com/file/d/1Wg8BxkVzGBNiqW-epfik3xHas1iM-hHT/view?usp=sharing
- Extension to easily discuss URIs
    * https://drive.google.com/file/d/1UR2LrjBrQuUj9JkcUl-He2TGvxezIhw0/view?usp=sharing
- An embed so that developers can embed discussions on stuff like articles, news, etc.
    * https://drive.google.com/file/d/19c5_l0LcZfZ_aC6S3JSdxauQMo1-JWK4/view?usp=sharing


*Current Status*
The browser extension will be the path to follow since it will be required to present by the end of July with the MVP features. This week was defined that we need to use “Blockstack” for the login process.

Here’s the current proposal following those requirements:
- https://drive.google.com/file/d/10ZiCztQEuTJ5EiDkYdOwJIq323vMMB1Y/view?usp=sharing


*For this concept discussions are always public and users have the ability to share discussions directly with other Blockstack IDs.

**Comment by satazor** [comment]
To mark this task as complete, we should put the links to the material into the README.md or DESIGN.md.

Thoughts @marcooliveira ?

**Comment by marcooliveira** [comment]
Yes, I'm working on getting this information organised here on Github, it's a bit different from what we're used to. I'll organise it and let you know.

**Comment by marcooliveira** [comment]
Based on the discussions today, let's organise this material under the repo. I'll be making the changes we discussed shortly.

**Comment by satazor** [comment]
Marking this as done, I'm organizing the repository as part of #42
